services:
  ocr-gpu:
    container_name: docling-easyocr-gpu
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr
    command: uvicorn main:app --port 8080 --host 0.0.0.0
    environment:
      - ENV=production
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
